# Generated by Django 6.0.8 on 2026-09-07 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "__first__"),
        ("patients", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="submitted_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_reports",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="maradministration",
            name="administered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mar_administrations",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="nursenote",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="nursenote",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="nurse_note",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_report",
                to="patients.nursenote",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="assigned_care_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_patients",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="nursenote",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nurse_notes",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="labresult",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lab_results",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_reports",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="maradministration",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="administrations",
                to="patients.prescription",
            ),
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="daily_reports", to="patients.reportphoto"
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vitals",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="vitalsign",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staffmember",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="maradministration",
            unique_together={("prescription", "day_number", "administered_at")},
        ),
    ]
