# Generated by Django 6.0.8 on 2026-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_encrypt_sensitive_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportphoto",
            name="image",
            field=models.FileField(upload_to="report_photos/%Y/%m/%d/"),
        ),
    ]
