# Generated by Django 6.0.8 on 2026-10-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_patient_portal_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"ordering": ["-created_at"]},
        ),
    ]
