# Generated by Django 6.0.8 on 2026-10-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0006_alter_patient_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin_dashboard", "Admin Dashboard"),
                    ("public_website", "Public Website"),
                    ("public_mobile_app", "Public Mobile App"),
                ],
                default="admin_dashboard",
                max_length=30,
            ),
        ),
    ]
