# Generated by Django 6.0.8 on 2026-09-16 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_assigned_staff_booking_patient"),
        ("staff", "0002_alter_staffmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="allergies",
            field=models.TextField(blank=True, default="NKDA"),
        ),
        migrations.AddField(
            model_name="booking",
            name="assigned_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="backup_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backup_bookings",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="care_manager_name",
            field=models.CharField(
                blank=True, default="Hina Malik (Care Coordinator)", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="clinical_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="consult_doctor_needed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="consultant_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="consultant_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="booking",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="booking",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="booking",
            name="gender_preference",
            field=models.CharField(
                choices=[
                    ("any", "No Preference"),
                    ("female", "Female Staff Only"),
                    ("male", "Male Staff Only"),
                ],
                default="any",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="has_prescription",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="patient_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="patient_dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                blank=True, default="cash_on_delivery", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="reference_code",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Booking Reference",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shift_duration",
            field=models.CharField(
                choices=[
                    ("1_hour", "1 Hour (Procedure)"),
                    ("2_hours", "2 Hours"),
                    ("4_hours", "4 Hours (Half Day)"),
                    ("8_hours", "8 Hours (Full Day/Night)"),
                    ("12_hours", "12 Hours (Extended Shift)"),
                    ("24_hours", "24 Hours (Full Bedside)"),
                ],
                default="4_hours",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="shift_frequency",
            field=models.CharField(
                choices=[
                    ("once", "Once (Single Visit)"),
                    ("daily", "Daily"),
                    ("alternate_days", "Alternate Days"),
                    ("twice_weekly", "Twice Weekly"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly Admission"),
                ],
                default="once",
                max_length=30,
            ),
        ),
    ]
