# Generated by Django 6.0.8 on 2026-09-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_allergies_booking_assigned_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="parent_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_instances",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="recurring_days",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("short_service", "Short Service"),
                    ("medicine_delivery", "Medicine Delivery"),
                    ("long_term", "Long-Term Care"),
                    ("long_term_admission", "Long-Term Admission"),
                    ("physiotherapy", "Physiotherapy & Rehabilitation"),
                    ("speech_therapy", "Speech & Language Therapy"),
                    ("psychotherapy", "Psychotherapy & Mental Health"),
                    ("dietician", "Clinical Nutrition & Dietetics"),
                    ("occupational", "Occupational Therapy"),
                ],
                max_length=30,
            ),
        ),
    ]
