# Generated by Django 6.0.8 on 2026-10-01 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "bookings",
            "0004_booking_parent_booking_booking_recurrence_end_date_and_more",
        ),
        ("patients", "0006_alter_patient_options"),
        ("staff", "0002_alter_staffmember_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerVisitChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_initial",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Staff Initial"
                    ),
                ),
                (
                    "pc_hygienic_measures",
                    models.TextField(blank=True, verbose_name="Hygienic Measures"),
                ),
                ("pc_mobility", models.TextField(blank=True, verbose_name="Mobility")),
                ("pc_diet", models.TextField(blank=True, verbose_name="Diet")),
                ("pc_bedsores", models.TextField(blank=True, verbose_name="Bedsores")),
                ("pc_grooming", models.TextField(blank=True, verbose_name="Grooming")),
                (
                    "pc_dressings",
                    models.TextField(
                        blank=True, verbose_name="Dressings (peg/trach/wound)"
                    ),
                ),
                (
                    "pc_catheter",
                    models.TextField(blank=True, verbose_name="NG/Foley's Catheter"),
                ),
                (
                    "pc_peripheral_central_line",
                    models.TextField(
                        blank=True, verbose_name="Peripheral and Central Line"
                    ),
                ),
                ("pc_bed_bath", models.TextField(blank=True, verbose_name="Bed Bath")),
                (
                    "sa_dress_code",
                    models.TextField(blank=True, verbose_name="Dress Code"),
                ),
                ("sa_uniform", models.TextField(blank=True, verbose_name="Uniform")),
                ("sa_shoes", models.TextField(blank=True, verbose_name="Shoes")),
                (
                    "sa_card",
                    models.TextField(blank=True, verbose_name="Card (ID Badge)"),
                ),
                ("sa_hygiene", models.TextField(blank=True, verbose_name="Hygiene")),
                ("sa_grooming", models.TextField(blank=True, verbose_name="Grooming")),
                (
                    "sp_with_family",
                    models.TextField(blank=True, verbose_name="Behaviour with Family"),
                ),
                (
                    "sp_with_patient",
                    models.TextField(blank=True, verbose_name="Behaviour with Patient"),
                ),
                (
                    "sp_with_colleagues",
                    models.TextField(
                        blank=True, verbose_name="Behaviour with Senior and Junior"
                    ),
                ),
                (
                    "sp_punctuality",
                    models.TextField(
                        blank=True, verbose_name="Punctuality and Attendance"
                    ),
                ),
                (
                    "sp_infection_control",
                    models.TextField(
                        blank=True, verbose_name="Infection Control Practices"
                    ),
                ),
                (
                    "sp_care_plan_adherence",
                    models.TextField(blank=True, verbose_name="Adherence to Care Plan"),
                ),
                (
                    "sp_burnout_signs",
                    models.TextField(blank=True, verbose_name="Any Sign of Burnout"),
                ),
                (
                    "sp_emergency_protocols",
                    models.TextField(blank=True, verbose_name="Emergency Protocols"),
                ),
                (
                    "doc_care_plan_update",
                    models.TextField(blank=True, verbose_name="Care Plan Update"),
                ),
                (
                    "doc_daily_records",
                    models.TextField(blank=True, verbose_name="Daily Records Accuracy"),
                ),
                (
                    "doc_mar_event_records",
                    models.TextField(blank=True, verbose_name="MAR / Event Records"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Manager Comments"),
                ),
                (
                    "family_concerns",
                    models.TextField(blank=True, verbose_name="Family's Concerns"),
                ),
                (
                    "staff_concerns",
                    models.TextField(blank=True, verbose_name="Staff's Concerns"),
                ),
                (
                    "manager_signature",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/checklist/manager/%Y/%m/",
                    ),
                ),
                (
                    "guardian_signature",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/checklist/guardian/%Y/%m/",
                    ),
                ),
                (
                    "staff_signature",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/checklist/staff/%Y/%m/",
                    ),
                ),
                ("visit_date", models.DateField(blank=True, null=True)),
                ("visit_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_checklists",
                        to="bookings.booking",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_checklists_submitted",
                        to="staff.staffmember",
                        verbose_name="Manager (filled by)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_checklists",
                        to="patients.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_checklists_as_evaluated",
                        to="staff.staffmember",
                        verbose_name="Visiting/Evaluated Staff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manager Home Visit Checklist",
                "verbose_name_plural": "Manager Home Visit Checklists",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time the call / booking was made",
                        null=True,
                    ),
                ),
                (
                    "attending_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Time staff arrived at patient location",
                        null=True,
                    ),
                ),
                (
                    "leaving_time",
                    models.DateTimeField(
                        blank=True, help_text="Time staff departed", null=True
                    ),
                ),
                ("prescription_by", models.CharField(blank=True, max_length=200)),
                (
                    "sign_of_reaction",
                    models.TextField(
                        blank=True, help_text="Any adverse reaction noted during visit"
                    ),
                ),
                (
                    "rating_professionalism",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Professionalism",
                    ),
                ),
                (
                    "rating_punctuality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Punctuality",
                    ),
                ),
                (
                    "rating_communication",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Communication and Behaviour",
                    ),
                ),
                (
                    "rating_hygiene",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Hygiene Maintenance",
                    ),
                ),
                (
                    "rating_privacy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Respect for Privacy",
                    ),
                ),
                (
                    "rating_clinical_skills",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Clinical Skills",
                    ),
                ),
                (
                    "rating_overall",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=10,
                        verbose_name="Overall Satisfaction",
                    ),
                ),
                ("suggestions", models.TextField(blank=True)),
                (
                    "patient_signature",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/signatures/patient/%Y/%m/",
                    ),
                ),
                ("patient_contact_number", models.CharField(blank=True, max_length=30)),
                (
                    "staff_signature",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="quality/signatures/staff/%Y/%m/",
                    ),
                ),
                (
                    "manager_quality_signature",
                    models.FileField(
                        blank=True,
                        help_text="Added later by a Quality Manager reviewing the form.",
                        null=True,
                        upload_to="quality/signatures/manager/%Y/%m/",
                    ),
                ),
                ("manager_signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_feedbacks",
                        to="bookings.booking",
                    ),
                ),
                (
                    "manager_signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_signed_feedbacks",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_feedbacks",
                        to="patients.patient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Attending staff member being evaluated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_feedbacks",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        help_text="Staff member who initiated the form (taken from JWT).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_feedbacks",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "vital_sign",
                    models.ForeignKey(
                        blank=True,
                        help_text="VitalSign record from this visit — avoids re-entry of vitals.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_forms",
                        to="patients.vitalsign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Quality Feedback",
                "verbose_name_plural": "Visit Quality Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
