import React, { useState } from 'react';
import { Printer, Download, X, FileText, CheckCircle, ShieldCheck } from 'lucide-react';
import useStore from '../store/useStore';
import { format } from 'date-fns';

export default function UniversalPrintButton({
  type = 'document',
  data = {},
  label = 'Print',
  variant = 'ghost',
  size = 'sm',
  iconOnly = false,
  showDownload = true,
  bulkData = null, // Array of records for bulk print
}) {
  const currentUser = useStore((s) => s.currentUser);
  const currentRole = useStore((s) => s.currentRole);
  const [showModal, setShowModal] = useState(false);

  const generatedBy = currentUser?.full_name || (currentRole ? currentRole.toUpperCase() : 'ADMIN STAFF');
  const timestamp   = format(new Date(), 'yyyy-MM-dd HH:mm:ss');

  const handleTriggerPrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    // Generate text/html blob for download
    const title = data.reference_code || data.mr_number || data.invoice_number || `HomeCare_Report_${type}_${Date.now()}`;
    const element = document.getElementById('printable-universal-document');
    if (!element) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Inter', sans-serif; padding: 20px; color: #611F8C; }
          .header { border-bottom: 2px solid #DE9A3C; padding-bottom: 12px; margin-bottom: 20px; }
          .title { font-size: 22px; font-weight: bold; color: #611F8C; }
          .meta { font-size: 11px; color: #6b7280; margin-top: 4px; }
          .section-title { font-size: 14px; font-weight: bold; margin-top: 16px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 12px; }
          th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
          th { background-color: #f3f4f6; font-weight: bold; }
          .footer { margin-top: 30px; font-size: 10px; color: #9ca3af; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
      </head>
      <body>
        ${element.innerHTML}
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title}.html`;
    a.click();
  };

  const recordsToPrint = bulkData && bulkData.length > 0 ? bulkData : [data];

  return (
    <>
      <button
        type="button"
        className={`btn btn-${variant} ${size === 'sm' ? 'btn-sm' : ''} ${iconOnly ? 'btn-icon' : ''}`}
        onClick={() => setShowModal(true)}
        title={label}
        style={{ gap: 6 }}
      >
        <Printer size={size === 'sm' ? 14 : 16} />
        {!iconOnly && <span>{label}</span>}
      </button>

      {/* Universal Print & Download Modal Preview */}
      {showModal && (
        <div className="modal-backdrop" onClick={(e) => e.target === e.currentTarget && setShowModal(false)}>
          <div className="modal" style={{ width: 720, maxHeight: '90vh', display: 'flex', flexDirection: 'column' }}>
            <div className="modal-header" style={{ background: 'var(--teal-800)', color: 'white' }}>
              <div>
                <h3 style={{ margin: 0, fontFamily: 'var(--font-heading)', color: 'white' }}>
                  Print Preview & Export — {type.toUpperCase().replace('_', ' ')}
                </h3>
                <div style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.7)', marginTop: 2 }}>
                  Generated by {generatedBy} on {timestamp}
                </div>
              </div>
              <button className="btn btn-ghost btn-icon" style={{ color: 'white' }} onClick={() => setShowModal(false)}>
                <X size={16} />
              </button>
            </div>

            <div className="modal-body" style={{ overflowY: 'auto', padding: 24, background: '#f9fafb' }}>
              
              {/* PRINTABLE CONTAINER (TARGETED BY CSS @media print) */}
              <div id="printable-universal-document" className="card" style={{ padding: 28, background: 'white', border: '1px solid var(--sage-200)' }}>
                
                {/* Header Banner */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: '2px solid var(--amber-500)', paddingBottom: 16, marginBottom: 20 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <img src="/ehealth-logo.png" alt="eHealth Logo" style={{ width: 36, height: 36, borderRadius: '50%', objectFit: 'cover' }} />
                    <div>
                      <h1 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.5rem', margin: 0, color: 'var(--teal-800)', fontWeight: 800 }}>
                        e<span style={{ color: 'var(--amber-500)' }}>Health</span>
                      </h1>
                      <div style={{ fontSize: '0.72rem', color: 'var(--status-grey)', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>
                        HOSPITAL AT HOME
                      </div>
                    </div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <span className="badge badge-teal" style={{ fontSize: '0.8rem', padding: '4px 10px' }}>
                      {type.toUpperCase().replace('_', ' ')}
                    </span>
                    <div style={{ fontSize: '0.72rem', color: 'var(--status-grey)', marginTop: 4, fontFamily: 'var(--font-mono)' }}>
                      Timestamp: {timestamp}
                    </div>
                  </div>
                </div>

                {/* Iterate over records (Supports Single & Bulk Print) */}
                {recordsToPrint.map((rec, idx) => (
                  <div key={idx} style={{ marginBottom: idx < recordsToPrint.length - 1 ? 30 : 0, pageBreakAfter: idx < recordsToPrint.length - 1 ? 'always' : 'auto' }}>
                    
                    {/* Record ID Metadata Header */}
                    <div style={{ background: 'var(--sage-50)', padding: 12, borderRadius: 8, marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <div>
                        <strong style={{ color: 'var(--teal-800)', fontSize: '0.9rem' }}>
                          Record Ref: {rec.reference_code || rec.mr_number || rec.invoice_number || `REC-${idx + 1}`}
                        </strong>
                        <div style={{ fontSize: '0.78rem', color: '#4b5563' }}>
                          Patient: {rec.patient_name || rec.full_name || rec.patient?.full_name || 'N/A'}
                        </div>
                      </div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--status-grey)', textAlign: 'right' }}>
                        <div>Issued By: {generatedBy}</div>
                        <div>Status: {rec.status_display || rec.status || 'Active'}</div>
                      </div>
                    </div>

                    {/* Specific Record Fields Rendering */}
                    {type === 'patient_summary' && (
                      <div style={{ fontSize: '0.84rem', lineHeight: 1.6 }}>
                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--teal-800)', marginBottom: 8 }}>Patient Clinical Profile</div>
                        <div><strong>Age / Gender:</strong> {rec.age}y · {rec.gender_display || rec.gender}</div>
                        <div><strong>Contact Phone:</strong> {rec.phone}</div>
                        <div><strong>Address:</strong> {rec.address}</div>
                        <div><strong>Primary Diagnosis:</strong> {rec.primary_diagnosis}</div>
                        <div><strong>Assigned Care Manager:</strong> {rec.care_manager_name || 'Hina Malik'}</div>
                        <div><strong>Allergies:</strong> {rec.allergies || 'NKDA'}</div>
                      </div>
                    )}

                    {type === 'daily_report' && (
                      <div style={{ fontSize: '0.84rem', lineHeight: 1.6 }}>
                        <div style={{ fontWeight: 700, fontSize: '0.9rem', color: 'var(--teal-800)', marginBottom: 8 }}>Nurse Clinical Visit Summary</div>
                        <div><strong>Nurse Name:</strong> {rec.nurse_name || 'Sarah Mitchell (RN)'}</div>
                        <div><strong>Vitals Recorded:</strong> BP {rec.vitals?.bp || '120/80'}, Pulse {rec.vitals?.pulse || '72'}, SpO2 {rec.vitals?.spo2 || '98%'}, Temp {rec.vitals?.temp || '98.6°F'}</div>
                        <div><strong>Clinical Notes:</strong> {rec.notes || 'Patient stable.'}</div>
                      </div>
                    )}

                    {type === 'invoice' && (
                      <div style={{ fontSize: '0.84rem' }}>
                        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 10 }}>
                          <thead>
                            <tr style={{ background: 'var(--sage-100)', color: 'var(--teal-800)' }}>
                              <th style={{ padding: 8, textAlign: 'left' }}>Item / Service</th>
                              <th style={{ padding: 8, textAlign: 'right' }}>Amount</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td style={{ padding: 8, borderBottom: '1px solid #eee' }}>{rec.service_package?.type || 'Home Care Package'}</td>
                              <td style={{ padding: 8, borderBottom: '1px solid #eee', textAlign: 'right' }}>PKR {(rec.total || 45000).toLocaleString()}</td>
                            </tr>
                          </tbody>
                        </table>
                        <div style={{ textAlign: 'right', marginTop: 10, fontWeight: 700, fontSize: '0.95rem', color: 'var(--teal-800)' }}>
                          Total Due: PKR {(rec.total || 45000).toLocaleString()}
                        </div>
                      </div>
                    )}

                    {type === 'booking_slip' && (
                      <div style={{ fontSize: '0.84rem', lineHeight: 1.6 }}>
                        <div style={{ fontWeight: 700, color: 'var(--teal-800)', marginBottom: 6 }}>Booking Schedule Details</div>
                        <div><strong>Scheduled Time:</strong> {rec.scheduled_time}</div>
                        <div><strong>Service Type:</strong> {rec.service_type_display || rec.service_type}</div>
                        <div><strong>Assigned Nurse:</strong> {rec.staff_name || rec.assigned_staff?.full_name || 'Unassigned'}</div>
                        <div><strong>Visit Location:</strong> {rec.address}</div>
                      </div>
                    )}

                    {type === 'attendance' && (
                      <div style={{ fontSize: '0.84rem', lineHeight: 1.6 }}>
                        <div style={{ fontWeight: 700, color: 'var(--teal-800)', marginBottom: 6 }}>Staff Attendance Sheet</div>
                        <div><strong>Staff Member:</strong> {rec.full_name || 'Sarah Mitchell'} ({rec.role_display || 'Nurse'})</div>
                        <div><strong>Employee ID:</strong> {rec.employee_id || 'N/A'}</div>
                        <div><strong>Status:</strong> {rec.status || 'Present'}</div>
                      </div>
                    )}

                    {type === 'id_card' && (
                      <div style={{ padding: 10, background: '#611F8C', color: 'white', borderRadius: 10, maxWidth: 360, margin: '0 auto' }}>
                        <div style={{ fontWeight: 700, fontSize: '1rem', color: '#DE9A3C' }}>eHealth Staff Digital ID Card</div>
                        <div style={{ fontSize: '0.9rem', marginTop: 4 }}>Name: {rec.full_name || 'Sarah Mitchell'}</div>
                        <div style={{ fontSize: '0.8rem', opacity: 0.9 }}>Role: {rec.role_display || 'Registered Nurse'}</div>
                        <div style={{ fontSize: '0.8rem', opacity: 0.9 }}>Staff ID: {rec.employee_id || 'HC-N-000123'}</div>
                        <div style={{ fontSize: '0.7rem', color: '#DE9A3C', marginTop: 8 }}>Real-Time QR Verification Encoded ✓</div>
                      </div>
                    )}

                    {type === 'nurses_notes' && (
                      <div style={{ fontSize: '0.84rem' }}>
                        <div style={{ background: '#f8fafc', padding: 12, border: '1px solid #cbd5e1', borderRadius: 6, marginBottom: 16 }}>
                          <div style={{ fontWeight: 800, fontSize: '0.95rem', color: 'var(--teal-800)', borderBottom: '1px solid #cbd5e1', paddingBottom: 6, marginBottom: 8 }}>
                            SOUTH EAST HOSPITAL / HOMECARE OS — NURSES NOTES SHEET (FORM A)
                          </div>
                          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10, fontSize: '0.8rem' }}>
                            <div><strong>MR #:</strong> {rec.patient?.mr_number || rec.mr_number || '—'}</div>
                            <div><strong>Patient:</strong> {rec.patient?.full_name || rec.full_name || 'Patient'}</div>
                            <div><strong>Doctor:</strong> {rec.patient?.care_manager_name || 'Attending Physician'}</div>
                          </div>
                        </div>
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.8rem' }}>
                          <thead>
                            <tr style={{ background: '#e2e8f0' }}>
                              <th style={{ border: '1px solid #cbd5e1', padding: 6, width: 130 }}>Date / Time</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 6 }}>Clinical Observation Note & Addenda</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 6, width: 170 }}>Digital Signature</th>
                            </tr>
                          </thead>
                          <tbody>
                            {(rec.nurseNotes || [rec]).map((note, nIdx) => (
                              <tr key={nIdx}>
                                <td style={{ border: '1px solid #cbd5e1', padding: 6, fontFamily: 'monospace', verticalAlign: 'top' }}>
                                  {format(new Date(note.recorded_at || new Date()), 'dd/MM/yyyy HH:mm')}
                                </td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 6, verticalAlign: 'top' }}>
                                  <div>{note.note}</div>
                                  {note.addenda?.map((a, aIdx) => (
                                    <div key={aIdx} style={{ marginTop: 6, paddingTop: 4, borderTop: '1px dashed #cbd5e1', fontSize: '0.76rem', color: '#1e293b' }}>
                                      <strong>Addendum:</strong> {a.text} <em>({a.created_by})</em>
                                    </div>
                                  ))}
                                </td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 6, verticalAlign: 'top', fontSize: '0.76rem', fontWeight: 'bold' }}>
                                  {note.recorded_by_name || 'Attending Nurse'}
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {type === 'vitals_history' && (
                      <div style={{ fontSize: '0.8rem' }}>
                        <div style={{ background: '#f8fafc', padding: 12, border: '1px solid #cbd5e1', borderRadius: 6, marginBottom: 16 }}>
                          <div style={{ fontWeight: 800, fontSize: '0.95rem', color: 'var(--teal-800)', borderBottom: '1px solid #cbd5e1', paddingBottom: 6, marginBottom: 8 }}>
                            SOUTH EAST HOSPITAL — FREQUENT VITAL SIGNS RECORD (FORM B)
                          </div>
                          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
                            <div><strong>Patient:</strong> {rec.patient?.full_name || rec.full_name || 'Patient'}</div>
                            <div><strong>MR #:</strong> {rec.patient?.mr_number || rec.mr_number || '—'}</div>
                            <div><strong>Consultant:</strong> {rec.patient?.care_manager_name || 'Attending Physician'}</div>
                          </div>
                        </div>
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.74rem', textAlign: 'center' }}>
                          <thead>
                            <tr style={{ background: '#1e293b', color: 'white' }}>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Date/Time</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>BP (sys/dia)</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Temp</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Pulse</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Resp</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>SpO2</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Intake (N/G | I/V)</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Output (Urine | Drain)</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>BSR & Insulin</th>
                              <th style={{ border: '1px solid #cbd5e1', padding: 5 }}>Staff</th>
                            </tr>
                          </thead>
                          <tbody>
                            {(rec.vitals || [rec]).map((v, vIdx) => (
                              <tr key={vIdx}>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5, fontFamily: 'monospace' }}>
                                  {format(new Date(v.recorded_at || new Date()), 'dd/MM HH:mm')}
                                </td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5, fontWeight: 'bold' }}>
                                  {v.blood_pressure_systolic ? `${v.blood_pressure_systolic}/${v.blood_pressure_diastolic}` : '—'}
                                </td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.temperature ? `${v.temperature}°C` : '—'}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.heart_rate || '—'}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.respiratory_rate || '—'}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5, fontWeight: 'bold' }}>{v.spo2 ? `${v.spo2}%` : '—'}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.intake_ng || 0} / {v.intake_iv || 0}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.output_urine || 0} / {v.output_drain || 0}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.bsr ? `${v.bsr} mg/dL` : '—'}</td>
                                <td style={{ border: '1px solid #cbd5e1', padding: 5 }}>{v.recorded_by_name || 'Attending Staff'}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {type === 'mar_sheet' && (
                      <div style={{ fontSize: '0.8rem' }}>
                        <div style={{ background: '#f8fafc', padding: 12, border: '1px solid #cbd5e1', borderRadius: 6, marginBottom: 16 }}>
                          <div style={{ fontWeight: 800, fontSize: '0.95rem', color: 'var(--teal-800)', borderBottom: '1px solid #cbd5e1', paddingBottom: 6, marginBottom: 8 }}>
                            SOUTH EAST HOSPITAL — DRUG ADMINISTRATION RECORD (MAR SHEET - FORM C)
                          </div>
                          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
                            <div><strong>Patient:</strong> {rec.patient?.full_name || rec.full_name || 'Patient'}</div>
                            <div><strong>MR #:</strong> {rec.patient?.mr_number || rec.mr_number || '—'}</div>
                            <div><strong>Consultant:</strong> {rec.patient?.care_manager_name || 'Attending Physician'}</div>
                          </div>
                        </div>

                        <div style={{ fontWeight: 'bold', marginBottom: 6, color: 'var(--teal-800)' }}>ACTIVE PRESCRIBED MEDICATIONS & 7-DAY ADMINISTRATION GRID</div>
                        {(rec.activeMeds || []).map((med, mIdx) => (
                          <div key={mIdx} style={{ border: '1px solid #cbd5e1', borderRadius: 6, padding: 8, marginBottom: 12 }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '0.85rem' }}>
                              <span>{med.brand_name} ({med.generic_name}) — {med.dose} [{med.route}]</span>
                              <span>Freq: {med.frequency}</span>
                            </div>
                            <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 6, fontSize: '0.72rem', textAlign: 'center' }}>
                              <thead>
                                <tr style={{ background: '#f1f5f9' }}>
                                  <th>Day 1</th><th>Day 2</th><th>Day 3</th><th>Day 4</th><th>Day 5</th><th>Day 6</th><th>Day 7 (Today)</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  {[1, 2, 3, 4, 5, 6, 7].map((d) => {
                                    const dayRec = med.days?.[d];
                                    return (
                                      <td key={d} style={{ border: '1px solid #e2e8f0', padding: 4 }}>
                                        {dayRec?.given ? (
                                          <div>
                                            <strong style={{ color: 'green' }}>✓ {dayRec.time}</strong>
                                            <div style={{ fontSize: '0.64rem', color: '#64748b' }}>{dayRec.nurse_name}</div>
                                          </div>
                                        ) : '—'}
                                      </td>
                                    );
                                  })}
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}

                {/* Footer Signature & Audit Trail */}
                <div style={{ marginTop: 40, borderTop: '1px solid var(--sage-200)', paddingTop: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', fontSize: '0.75rem', color: 'var(--status-grey)' }}>
                  <div>
                    <div>Generated via HomeCare OS Universal Report Engine</div>
                    <div>Security Audit Hash: {Math.random().toString(36).substring(2, 10).toUpperCase()}</div>
                  </div>
                  <div style={{ textAlign: 'center' }}>
                    <div style={{ borderBottom: '1px solid #9ca3af', width: 140, marginBottom: 4 }}></div>
                    <div>Authorized Signature</div>
                  </div>
                </div>
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn btn-ghost" onClick={() => setShowModal(false)}>Close</button>
              {showDownload && (
                <button className="btn btn-ghost" onClick={handleDownloadPDF} style={{ gap: 6 }}>
                  <Download size={14} /> Download HTML/PDF File
                </button>
              )}
              <button className="btn btn-primary" onClick={handleTriggerPrint} style={{ gap: 6 }}>
                <Printer size={14} /> Print Document →
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
