# Generated by Django 6.0.8 on 2026-09-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livevisit",
            options={"ordering": ["-last_update"]},
        ),
    ]
