# Generated by Django 6.0.8 on 2026-09-14 20:53

import django.db.models.deletion
import lms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0002_alter_staffmember_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("onboarding", "New Staff Onboarding"),
                            ("clinical", "Clinical Skills"),
                            ("compliance", "Compliance & Safety"),
                            ("leadership", "Leadership & Management"),
                            ("technology", "Technology & Systems"),
                            ("soft_skills", "Soft Skills"),
                            ("other", "Other"),
                        ],
                        default="onboarding",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lms_courses_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lms_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="lms.course",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_date"],
                "unique_together": {("staff", "course")},
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        default=lms.models._cert_number, max_length=20, unique=True
                    ),
                ),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, upload_to="lms/certificates/"),
                ),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="lms.courseassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_date"],
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="lms/videos/"),
                ),
                ("video_url", models.URLField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Expected duration in seconds"
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="lms.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
                "unique_together": {("course", "order")},
            },
        ),
        migrations.CreateModel(
            name="LectureProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("completed", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_progresses",
                        to="lms.courseassignment",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresses",
                        to="lms.lecture",
                    ),
                ),
            ],
            options={
                "unique_together": {("assignment", "lecture")},
            },
        ),
    ]
