# Generated by Django 6.0.8 on 2026-09-14 21:42

import django.db.models.deletion
import django.utils.timezone
import lms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
        ("staff", "0002_alter_staffmember_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["-issue_date", "-id"]},
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="issued_date",
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_id",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name="certificate",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="certificate",
            name="generated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates_generated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="certificate",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="certificate",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="staff.staffmember",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="title",
            field=models.CharField(default="Certificate of Completion", max_length=255),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="assignment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate",
                to="lms.courseassignment",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="certificate_number",
            field=models.CharField(
                default=lms.models._cert_id, max_length=50, unique=True
            ),
        ),
    ]
