# Generated by Django 6.0.8 on 2026-09-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("nurse", "Nurse"),
                    ("doctor", "Doctor"),
                    ("physio", "Physiotherapist"),
                    ("speech", "Speech & Language Therapist"),
                    ("psychologist", "Psychologist"),
                    ("dietician", "Dietician"),
                    ("care_manager", "Client Care Manager"),
                    ("branch_manager", "Branch Manager"),
                    ("admin", "Admin"),
                    ("accountant", "Accountant"),
                    ("crm_executive", "CRM Executive"),
                ],
                max_length=20,
            ),
        ),
    ]
