import io
from datetime import datetime

class HomeCarePDFGenerator:
    """
    Universal PDF Report Engine for HomeCare OS.
    Generates branded PDF documents for:
    - Nurse Daily Patient Report
    - Patient 360° Profile Summary
    - Invoice
    - Attendance Monthly Summary
    - Booking Confirmation Slip
    - Leave Approval Slip
    - Analytics Export
    - LMS Course Completion Certificate  ← NEW
    """
    
    PRIMARY_TEAL = "#123832"
    ACCENT_AMBER = "#DE9A3C"
    BG_SAGE = "#DCE8DE"

    def __init__(self, report_type, data, generated_by="Admin"):
        self.report_type = report_type
        self.data = data
        self.generated_by = generated_by
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def generate(self):
        buffer = io.BytesIO()
        try:
            from reportlab.lib.pagesizes import letter, A4
            from reportlab.lib import colors
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.enums import TA_CENTER, TA_LEFT

            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=36,
                leftMargin=36,
                topMargin=36,
                bottomMargin=36
            )
            styles = getSampleStyleSheet()
            elements = []

            # Shared styles
            title_style = ParagraphStyle(
                'DocTitle',
                parent=styles['Heading1'],
                fontSize=20,
                textColor=colors.HexColor(self.PRIMARY_TEAL),
                spaceAfter=6
            )
            sub_style = ParagraphStyle(
                'DocSub',
                parent=styles['Normal'],
                fontSize=9,
                textColor=colors.HexColor("#6b7280"),
                spaceAfter=15
            )

            # ── CERTIFICATE branch (Official eHealth Landscape A4 Template) ────
            if self.report_type == 'certificate':
                return self._generate_official_certificate(buffer)

            # ── INVOICE branch ────────────────────────────────────────────────
            elif self.report_type == 'invoice':
                elements.append(Paragraph("<b>HomeCare OS</b> — Healthcare PDF Report", title_style))
                elements.append(Paragraph(f"Report Type: {self.report_type.upper()} | Generated: {self.timestamp} by {self.generated_by}", sub_style))
                elements.append(Paragraph(f"<b>Invoice #:</b> {self.data.get('invoice_number', 'INV-001')}", styles['Heading2']))
                elements.append(Paragraph(f"<b>Patient:</b> {self.data.get('patient_name', 'N/A')}", styles['Normal']))
                elements.append(Paragraph(f"<b>Total Due:</b> PKR {self.data.get('total', 0)}", styles['Normal']))

            # ── DAILY REPORT branch ───────────────────────────────────────────
            elif self.report_type == 'daily_report':
                elements.append(Paragraph("<b>HomeCare OS</b> — Healthcare PDF Report", title_style))
                elements.append(Paragraph(f"Report Type: {self.report_type.upper()} | Generated: {self.timestamp} by {self.generated_by}", sub_style))
                elements.append(Paragraph(f"<b>Daily Visit Report:</b> {self.data.get('patient_name', 'N/A')}", styles['Heading2']))
                elements.append(Paragraph(f"<b>Nurse:</b> {self.data.get('nurse_name', 'N/A')}", styles['Normal']))
                elements.append(Paragraph(f"<b>Notes:</b> {self.data.get('notes', 'No notes')}", styles['Normal']))

            # ── GENERIC fallback ──────────────────────────────────────────────
            else:
                elements.append(Paragraph("<b>HomeCare OS</b> — Healthcare PDF Report", title_style))
                elements.append(Paragraph(f"Report Type: {self.report_type.upper()} | Generated: {self.timestamp} by {self.generated_by}", sub_style))
                elements.append(Paragraph(f"<b>Summary:</b> {str(self.data)}", styles['Normal']))

            elements.append(Spacer(1, 20))
            if self.report_type != 'certificate':
                elements.append(Paragraph("<i>Official Record generated by HomeCare OS Enterprise Engine</i>", sub_style))

            doc.build(elements)
            pdf = buffer.getvalue()
            buffer.close()
            return pdf
        except ImportError:
            # Fallback if ReportLab is missing in environment
            buffer.write(f"HomeCare OS PDF Report\nType: {self.report_type}\nDate: {self.timestamp}\nData: {self.data}".encode('utf-8'))
            return buffer.getvalue()

    def _generate_official_certificate(self, buffer):
        """
        Generate official printed certificate matching the company's official template:
        - Landscape A4 (297mm x 210mm)
        - Color palette: Deep Purple/Maroon (#5B1A4A), Gold Accent (#D4A94A), Light Gray (#E5E7EB)
        - Corner decoration: Multi-layer geometric triangles (purple, dark facet, gray accent, thin diagonal gold lines)
        - Header: eHealth interlocking logo + gold 'eHealth' wordmark + 'HOSPITAL AT HOME'
        - Registered seals: 'Registered with IHRA' (top-right) & 'Registered with SECP' (bottom-right)
        - Script 'Certificate' + 'for' + Dynamic Achievement Title + 'This is to certify that' + Recipient Name + Description
        - Footer: Issue date, Authorized Signatory line, live QR verification code + Certificate ID
        """
        import os
        from django.conf import settings
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
        import qrcode

        PAGE_WIDTH, PAGE_HEIGHT = landscape(A4)

        PURPLE_DARK = colors.HexColor('#441337')
        PURPLE_MAIN = colors.HexColor('#5B1A4A')
        PURPLE_MID  = colors.HexColor('#7A2359')
        GOLD_ACCENT = colors.HexColor('#D4A94A')
        GRAY_LIGHT  = colors.HexColor('#E5E7EB')
        TEXT_DARK   = colors.HexColor('#1F2937')
        TEXT_MUTED  = colors.HexColor('#6B7280')

        def draw_seal(canvas, x, y, r, title, subtitle):
            canvas.saveState()
            canvas.setStrokeColor(GOLD_ACCENT)
            canvas.setLineWidth(1.6)
            canvas.setFillColor(colors.HexColor('#FCFBF9'))
            canvas.circle(x, y, r, fill=True, stroke=True)
            canvas.setLineWidth(0.7)
            canvas.circle(x, y, r - 3, fill=False, stroke=True)
            canvas.setFillColor(PURPLE_MID)
            canvas.setFont('Helvetica-Bold', 4.5)
            canvas.drawCentredString(x, y + 8, subtitle)
            canvas.setFont('Helvetica-Bold', 8.5)
            canvas.setFillColor(PURPLE_MAIN)
            canvas.drawCentredString(x, y - 2, title)
            canvas.setFont('Helvetica', 5)
            canvas.setFillColor(GOLD_ACCENT)
            canvas.drawCentredString(x, y - 11, "★ REGD. OFFICIAL ★")
            canvas.restoreState()

        def draw_background(canvas, doc):
            canvas.saveState()
            w, h = doc.pagesize

            # Clean white background
            canvas.setFillColor(colors.white)
            canvas.rect(0, 0, w, h, fill=True, stroke=False)

            # ── Top-Left Corner Geometric Decoration ──
            # 1. Light gray overlapping triangle
            canvas.setFillColor(GRAY_LIGHT)
            p1 = canvas.beginPath()
            p1.moveTo(0, h)
            p1.lineTo(240, h)
            p1.lineTo(0, h - 175)
            p1.close()
            canvas.drawPath(p1, fill=True, stroke=False)

            # 2. Main Deep Purple triangle
            canvas.setFillColor(PURPLE_MAIN)
            p2 = canvas.beginPath()
            p2.moveTo(0, h)
            p2.lineTo(210, h)
            p2.lineTo(0, h - 150)
            p2.close()
            canvas.drawPath(p2, fill=True, stroke=False)

            # 3. Inner Dark facet
            canvas.setFillColor(PURPLE_DARK)
            p3 = canvas.beginPath()
            p3.moveTo(0, h)
            p3.lineTo(115, h)
            p3.lineTo(0, h - 85)
            p3.close()
            canvas.drawPath(p3, fill=True, stroke=False)

            # 4. Gold diagonal accent lines
            canvas.setStrokeColor(GOLD_ACCENT)
            canvas.setLineWidth(2.5)
            canvas.line(0, h - 158, 222, h)
            canvas.setLineWidth(1)
            canvas.line(0, h - 165, 232, h)

            # ── Bottom-Right Corner Geometric Decoration ──
            # 1. Light gray overlapping triangle
            canvas.setFillColor(GRAY_LIGHT)
            p4 = canvas.beginPath()
            p4.moveTo(w, 0)
            p4.lineTo(w - 240, 0)
            p4.lineTo(w, 175)
            p4.close()
            canvas.drawPath(p4, fill=True, stroke=False)

            # 2. Main Deep Purple triangle
            canvas.setFillColor(PURPLE_MAIN)
            p5 = canvas.beginPath()
            p5.moveTo(w, 0)
            p5.lineTo(w - 210, 0)
            p5.lineTo(w, 150)
            p5.close()
            canvas.drawPath(p5, fill=True, stroke=False)

            # 3. Inner Dark facet
            canvas.setFillColor(PURPLE_DARK)
            p6 = canvas.beginPath()
            p6.moveTo(w, 0)
            p6.lineTo(w - 115, 0)
            p6.lineTo(w, 85)
            p6.close()
            canvas.drawPath(p6, fill=True, stroke=False)

            # 4. Gold diagonal accent lines
            canvas.setStrokeColor(GOLD_ACCENT)
            canvas.setLineWidth(2.5)
            canvas.line(w - 222, 0, w, 158)
            canvas.setLineWidth(1)
            canvas.line(w - 232, 0, w, 165)

            # ── Fixed Registration Seals (Authentic Company Details) ──
            # Top-right seal: Registered with IHRA
            draw_seal(canvas, w - 85, h - 80, 27, "IHRA", "REGD. WITH")
            # Bottom-right seal: Registered with SECP
            draw_seal(canvas, w - 85, 110, 27, "SECP", "REGD. WITH")

            canvas.restoreState()

        # Build Document
        doc = SimpleDocTemplate(
            buffer,
            pagesize=(PAGE_WIDTH, PAGE_HEIGHT),
            leftMargin=90,
            rightMargin=90,
            topMargin=42,
            bottomMargin=38
        )

        elements = []

        # Extract data with safe fallbacks
        cert_id = self.data.get('certificate_id') or self.data.get('certificate_number', 'CERT-2026-000001')
        recipient_name = self.data.get('recipient_name') or self.data.get('staff_name', 'Valued Staff Member')
        title = self.data.get('title') or self.data.get('course_title', 'Certificate of Completion')
        description = self.data.get('description') or 'For successfully completing all requirements and demonstrating professional clinical excellence.'
        issue_date = self.data.get('issue_date') or self.data.get('issued_date', datetime.now().strftime('%d %B %Y'))
        verify_url = self.data.get('verification_url') or f"http://localhost:5173/verify-certificate/{cert_id}"

        # Real QR Code Flowable
        qr = qrcode.QRCode(version=1, box_size=3, border=1)
        qr.add_data(verify_url)
        qr.make(fit=True)
        qr_img = qr.make_image(fill_color="#5B1A4A", back_color="white")
        qr_buf = io.BytesIO()
        qr_img.save(qr_buf)
        qr_buf.seek(0)
        qr_flowable = RLImage(qr_buf, width=46, height=46)

        # 1. Header (Logo + eHealth wordmark + Hospital At Home subtitle)
        logo_path = os.path.join(settings.BASE_DIR, '..', 'frontend', 'public', 'ehealth-logo.png')
        if not os.path.exists(logo_path):
            logo_path = r"C:\Users\Administrator\Desktop\health\frontend\public\ehealth-logo.png"

        if os.path.exists(logo_path):
            header_logo = RLImage(logo_path, width=42, height=42)
        else:
            header_logo = Paragraph("<b><font color='#5B1A4A' size='22'>eH</font></b>", ParagraphStyle('LogoFallback', alignment=TA_CENTER))

        header_text = [
            Paragraph('<b>eHealth</b>', ParagraphStyle('BrandWord', fontName='Helvetica-Bold', fontSize=22, leading=24, textColor=GOLD_ACCENT, alignment=TA_CENTER)),
            Spacer(1, 2),
            Paragraph('HOSPITAL AT HOME', ParagraphStyle('BrandSub', fontName='Helvetica-Bold', fontSize=7.5, leading=10, textColor=PURPLE_MID, alignment=TA_CENTER, letterSpacing=2.5)),
        ]

        header_table = Table([[header_logo, header_text]], colWidths=[48, 200], hAlign='CENTER')
        header_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        elements.append(header_table)
        elements.append(Spacer(1, 10))

        # 2. "Certificate" script title
        elements.append(Paragraph(
            "Certificate",
            ParagraphStyle('CertScript', fontName='Times-BoldItalic', fontSize=46, leading=50, textColor=PURPLE_MAIN, alignment=TA_CENTER)
        ))
        elements.append(Spacer(1, 4))

        # 3. "for" connective
        elements.append(Paragraph(
            "for",
            ParagraphStyle('ForWord', fontName='Helvetica', fontSize=10, leading=14, textColor=TEXT_MUTED, alignment=TA_CENTER)
        ))
        elements.append(Spacer(1, 4))

        # 4. Achievement / Award Title (Dynamic per certificate)
        elements.append(Paragraph(
            title.upper(),
            ParagraphStyle('AchieveTitle', fontName='Helvetica-Bold', fontSize=21, leading=26, textColor=GOLD_ACCENT, alignment=TA_CENTER, letterSpacing=2)
        ))
        elements.append(Spacer(1, 6))

        # 5. "This is to certify that"
        elements.append(Paragraph(
            "This is to certify that",
            ParagraphStyle('CertifyLine', fontName='Helvetica', fontSize=11, leading=15, textColor=TEXT_MUTED, alignment=TA_CENTER)
        ))
        elements.append(Spacer(1, 4))

        # 6. Recipient Full Name (Prominently displayed)
        elements.append(Paragraph(
            f"<u><b>{recipient_name}</b></u>",
            ParagraphStyle('RecipName', fontName='Times-BoldItalic', fontSize=28, leading=34, textColor=PURPLE_MAIN, alignment=TA_CENTER)
        ))
        elements.append(Spacer(1, 8))

        # 7. Description Paragraph (Dynamic per certificate)
        elements.append(Paragraph(
            description,
            ParagraphStyle('DescText', fontName='Helvetica', fontSize=10, leading=15, textColor=TEXT_DARK, alignment=TA_CENTER)
        ))
        elements.append(Spacer(1, 24))

        # 8. Footer Row: Date & Signature (Left) + Verification QR & ID (Right)
        sig_col = [
            Paragraph(f"<b>Date:</b> {issue_date}", ParagraphStyle('DateP', fontName='Helvetica', fontSize=9, leading=12, textColor=TEXT_DARK)),
            Spacer(1, 12),
            Paragraph("______________________________________", ParagraphStyle('SigLine', fontName='Helvetica', fontSize=8.5, leading=10, textColor=TEXT_MUTED)),
            Paragraph("<b>Authorized Signatory</b>", ParagraphStyle('SigTitle', fontName='Helvetica-Bold', fontSize=8, leading=11, textColor=PURPLE_MAIN)),
            Paragraph("eHealth Hospital At Home · Islamabad, Pakistan", ParagraphStyle('SigSub', fontName='Helvetica', fontSize=7, leading=9, textColor=TEXT_MUTED)),
        ]

        verify_col = [
            Table([[
                qr_flowable,
                [
                    Paragraph("<b>Certificate ID:</b>", ParagraphStyle('QrLbl', fontName='Helvetica', fontSize=7, leading=9, textColor=TEXT_MUTED)),
                    Paragraph(f"<b><font color='#5B1A4A'>{cert_id}</font></b>", ParagraphStyle('QrId', fontName='Courier-Bold', fontSize=8.5, leading=11)),
                    Paragraph("Scan QR code to verify authenticity", ParagraphStyle('QrSub', fontName='Helvetica', fontSize=6.5, leading=8.5, textColor=TEXT_MUTED)),
                    Paragraph("ihra.gov.pk · secp.gov.pk registered", ParagraphStyle('QrSub2', fontName='Helvetica', fontSize=6.5, leading=8.5, textColor=GOLD_ACCENT)),
                ]
            ]], colWidths=[48, 160], hAlign='RIGHT')
        ]

        footer_table = Table([[sig_col, verify_col]], colWidths=[360, 280])
        footer_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'BOTTOM'),
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('TOPPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ]))
        elements.append(footer_table)

        doc.build(elements, onFirstPage=draw_background)
        pdf = buffer.getvalue()
        buffer.close()
        return pdf

